networks:
  ingress:
    name: ingress
    driver: bridge

  services:
    name: services
    driver: bridge

  vpn-isolated:
    name: vpn-isolated
    driver: bridge

  immich:
    name: immich
    driver: bridge

services: {}

include:
  - cloudflare-tunnel/compose.yaml
  - traefik/compose.yaml
  - adguard/compose.yaml
  - immich/compose.yaml
  - arr/compose.yaml
  - dashdot/compose.yaml
  - restic/compose.yaml
